### ISSUE TITLE
Equivalent Babel Plugin?

### ISSUE THREAD

**Issue by tomatau** [shaketbaby/directory-named-webpack-plugin#9] opened 2017-01-22 10:19 UTC
This plugin looks great! However in an isomorphic app it's a no-go unless you're webpacking your node code. If there's an equivalent babel plugin, that would be great! I had a good look around but couldn't find one.

**Comment by shaketbaby** [comment] 2017-01-25 01:02
I was building this plugin specifically for Webpack. Not very familiar with creating Babel plugins, but based on my understanding of what Babel does, it seems this is not really Babel's responsibility. Maybe what's needed is an equivalent thing for node.js?

**Comment by tomatau** [comment] 2017-01-25 19:51
Often people use babel runtime compilation for server side renders of isomorphic apps (as they need to compile JSX) to keep the codebase all with the same language features. Especially if they can't use the latest node. In this case it's normal to use the babelrc configuration for the server side code.

**Comment by shaketbaby** [comment] 2017-01-26 23:41
I thought all Babel does is to transpile the given string in es2015 or any format supported to es5 JavaScript code. It doesn't really resolve the path itself, that part is done by Webpack, Browserify, Node.js, etc. My understanding is if Babel sees an `import foo from "foo"`, it just transpiles that to `var foo = require("foo")`, and leave the actual path resolving to other tools. I need to learn more about Babel, but are you saying that Babel will try to resolve the path itself?

**Comment by tomatau** [comment] 2017-01-27 17:26
You can use babel without Webpack and in that case it can handle resolving paths.

**Comment by shaketbaby** [comment] 2017-01-29 22:34
Would you please be able to point me to some links/articles that explain how this works? When I use Babel on the server, it is `Node.js` that does the resolving. So if you could provide some info about that, that'd be great!

**Comment by shaketbaby** [comment] 2017-01-29 22:49
Just had a look at the https://babeljs.io/docs/usage/babel-register/ and looks like my understanding is not correct, and there's an option `resolveModuleSource` which seems something can be used, will look into it.

**Comment by tomatau** [comment] 2017-01-30 17:53
It might be worth having a look at how https://github.com/tleunen/babel-plugin-module-resolver achieves the resolution for babel. I'm guessing it would map import paths to require calls in compilation using absolute paths. I guess it would be much trickier as an alias is a straight swap whereas this functionality is more dynamic to the existence of files.

**Comment by mdluo** [comment] 2017-03-02 12:33
+1

**Comment by IgnusG** [comment] 2017-04-06 12:14
I found [this plugin](https://github.com/mdluo/babel-plugin-directory-named-module) but it's not published on npm despite saying so

**Comment by tomatau** [comment] 2017-04-06 13:05
Oh nice! Did you see it working @IgnusG ? Might be worth publishing it anyway

**Comment by mdluo** [comment] 2017-04-07 02:51
@IgnusG 

A month ago I was seeking for the equivalent babel plugin too and I was here to [+1](https://github.com/shaketbaby/directory-named-webpack-plugin/issues/9#issuecomment-283641670). But there's no such plugin really works

So I wrote the plugin myself and all tests passed. However it doesn't work with my webpack and babel config. I don't know where the problem is and it may cost me much more time to solve it rather than just adding few `index.js`s. So I unpublished the module from npm. 

Besides, you can try to install it directly from GitHub:

```
npm install --save-dev https://github.com/mdluo/babel-plugin-directory-named-module.git
```

And PRs are welcomed 😎

Ref: https://github.com/mdluo/babel-plugin-directory-named-module/issues/1

**Comment by shaketbaby** [comment] 2017-04-30 23:29
If both Webpack and Babel are used, then probably just let Webpack does the resolving. And the Bebal plugin is perhaps only needed when Babel is used alone.

**Comment by shaketbaby** [comment] 2017-05-02 07:59
Closing now given @mdluo has created a repo for this.

**Closed by shaketbaby** 2017-05-02 07:59 UTC

**Comment by gkiely** [comment] 2018-01-11 21:19
For anyone looking for a solution to this: I moved from using `babel-plugin-module-resolver` for my aliases to `alias` in webpack and this plugin worked fine. Using webpack 3.10.0
